# Generated by Django 4.0 on 2021-12-20 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vkapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='auth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='search_category',
        ),
        migrations.AddField(
            model_name='user',
            name='catalog',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='main_info',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vkapi.category')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vkapi.user')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vkapi.user'),
        ),
    ]
