# Generated by Django 4.0.1 on 2022-01-19 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vkapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(default=None, max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='groups',
            field=models.CharField(default=None, max_length=30, verbose_name='Группы'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='vkapi.category'),
        ),
    ]
