# Generated by Django 4.0.1 on 2022-01-19 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vkapi', '0002_alter_category_category_name_alter_category_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=20, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='groups',
            field=models.CharField(max_length=30, null=True, verbose_name='Группы'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vkapi.category'),
        ),
    ]
