# Generated by Django 4.0 on 2021-12-22 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('vkapi', '0003_remove_data_info_remove_groups_domain_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Main',
        ),
    ]
