# Generated by Django 4.0.1 on 2022-01-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkapi', '0003_alter_category_category_name_alter_category_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='key_word',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
