# Generated by Django 4.0.1 on 2022-01-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkapi', '0004_alter_subscription_key_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='groups',
        ),
        migrations.AddField(
            model_name='category',
            name='group_one',
            field=models.CharField(max_length=30, null=True, verbose_name='Группа 1'),
        ),
        migrations.AddField(
            model_name='category',
            name='group_three',
            field=models.CharField(max_length=30, null=True, verbose_name='Группа 3'),
        ),
        migrations.AddField(
            model_name='category',
            name='group_two',
            field=models.CharField(max_length=30, null=True, verbose_name='Группа 2'),
        ),
    ]
